<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@3.8">
  <node class="cps.n.StepAtomNode" plugin="workflow-cps@2.94">
    <parentIds>
      <string>68</string>
    </parentIds>
    <id>69</id>
    <descriptorId>org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep</descriptorId>
  </node>
  <actions>
    <cps.a.ArgumentsActionImpl plugin="workflow-cps@2.94">
      <arguments>
        <entry>
          <string>script</string>
          <string>
                            if [ ! -d &quot;config/default&quot; ]; then
                              mkdir -p config/default
                            fi
                            wget -r -np -nd -erobots=off -A &apos;*.json&apos; --reject-regex &apos;/\*.+\*/|auto_refresh&apos; --no-check-certificate --auth-no-challenge --user=&apos;${apiUser}&apos; --password=&apos;${PwdApiUser}&apos;  &apos;https://jenkins-agi-apps-production.apps.ocp.so.ch/job/gdi/job/qgis-server/1399/artifact/config/default/&apos; -P qgs
                            python3 /srv/json2qgs/json2qgs.py qgs/somap.json wms ./config/default 2 --qgsName somap --qgsTemplateDir /srv/json2qgs/qgs
                            python3 /srv/json2qgs/json2qgs.py qgs/somap_print.json wms ./config/default 2 --qgsName somap_print --qgsTemplateDir /srv/json2qgs/qgs
                            python3 /srv/json2qgs/json2qgs.py qgs/somap_wfs.json wfs ./config/default 2 --qgsName somap_wfs --qgsTemplateDir /srv/json2qgs/qgs
                        </string>
        </entry>
      </arguments>
      <sensitiveVariables>
        <string>PwdSogisService</string>
        <string>PwdApiUser</string>
        <string>PwdOgcServer</string>
        <string>apiUser</string>
      </sensitiveVariables>
      <isUnmodifiedBySanitization>false</isUnmodifiedBySanitization>
    </cps.a.ArgumentsActionImpl>
    <wf.a.TimingAction plugin="workflow-api@2.47">
      <startTime>1665498378257</startTime>
    </wf.a.TimingAction>
    <s.a.LogStorageAction/>
    <wf.a.ErrorAction plugin="workflow-api@2.47">
      <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@2.24">
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.interrupt(CpsFlowExecution.java:1147)</trace>
          <trace>org.jenkinsci.plugins.workflow.job.WorkflowRun$2.lambda$interrupt$0(WorkflowRun.java:396)</trace>
          <trace>jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions class="empty-list"/>
        <result>
          <name>ABORTED</name>
          <ordinal>4</ordinal>
          <color>ABORTED</color>
          <completeBuild>false</completeBuild>
        </result>
        <causes class="java.util.Arrays$ArrayList">
          <a class="jenkins.model.CauseOfInterruption-array">
            <org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerCancelledCause plugin="pipeline-build-step@2.15">
              <cause class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@2.24">
                <stackTrace>
                  <trace>org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.cancel(CpsBodyExecution.java:253)</trace>
                  <trace>org.jenkinsci.plugins.workflow.steps.BodyExecution.cancel(BodyExecution.java:76)</trace>
                  <trace>org.jenkinsci.plugins.workflow.cps.steps.ParallelStepExecution.stop(ParallelStepExecution.java:68)</trace>
                  <trace>org.jenkinsci.plugins.workflow.cps.CpsThread.stop(CpsThread.java:319)</trace>
                  <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1161)</trace>
                  <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1150)</trace>
                  <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:917)</trace>
                  <trace>org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)</trace>
                  <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
                  <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
                  <trace>hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)</trace>
                  <trace>jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)</trace>
                  <trace>jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)</trace>
                  <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
                  <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
                  <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
                  <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
                  <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
                </stackTrace>
                <suppressedExceptions class="empty-list"/>
                <result>
                  <name>ABORTED</name>
                  <ordinal>4</ordinal>
                  <color>ABORTED</color>
                  <completeBuild>false</completeBuild>
                </result>
                <causes class="java.util.Arrays$ArrayList">
                  <a class="jenkins.model.CauseOfInterruption-array">
                    <org.jenkinsci.plugins.workflow.steps.ExceptionCause>
                      <t class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException">
                        <stackTrace>
                          <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.interrupt(CpsFlowExecution.java:1147)</trace>
                          <trace>org.jenkinsci.plugins.workflow.job.WorkflowRun$2.lambda$interrupt$0(WorkflowRun.java:396)</trace>
                          <trace>jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)</trace>
                          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
                          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
                          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
                          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
                          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
                          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
                        </stackTrace>
                        <suppressedExceptions class="empty-list"/>
                        <result>
                          <name>NOT_BUILT</name>
                          <ordinal>3</ordinal>
                          <color>NOTBUILT</color>
                          <completeBuild>false</completeBuild>
                        </result>
                        <causes class="java.util.Arrays$ArrayList">
                          <a class="jenkins.model.CauseOfInterruption-array">
                            <org.jenkinsci.plugins.pipeline.milestone.CancelledCause plugin="pipeline-milestone-step@1.3.2">
                              <newerBuild>WebGISClient#1464</newerBuild>
                              <displayName>WebGISClient#1464</displayName>
                            </org.jenkinsci.plugins.pipeline.milestone.CancelledCause>
                          </a>
                        </causes>
                        <actualInterruption>true</actualInterruption>
                      </t>
                    </org.jenkinsci.plugins.workflow.steps.ExceptionCause>
                  </a>
                </causes>
                <actualInterruption>true</actualInterruption>
              </cause>
            </org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerCancelledCause>
          </a>
        </causes>
        <actualInterruption>true</actualInterruption>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>